### ISSUE TITLE
assembleCreateAllFileRelease 报错

### ISSUE THREAD

**Issue by jiyuren** [wgllss/WXDynamicPlugin#5]
现在报的是这个错误了，刚才的是我工作路径后面少了斜杠，Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @5a19245c

**Comment by wgllss** [comment]
配置的工作目录里面有 d8.bat 文件么？

**Comment by jiyuren** [comment]
> 配置的工作目录里面 workingDirPath 里面 有 d8.bat 文件么？ 是不是mac 编译的？AS 最新版吗？

有d8.bat ,windows 编译，是最新的AS 考拉

**Comment by jiyuren** [comment]
> 配置的工作目录里面 workingDirPath 里面 有 d8.bat 文件么？ 是不是mac 编译的？AS 最新版吗？

是我这边工作路径写错了，少了后面的斜杠，现在报的是这个错误，只生成了这几个文件，0classes business lib dex0classes common dex0classes home dex0classes loading dex0classes_manager dex0classes other dex0classes other2 dex0classes version dex， Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @5a19245c

**Comment by jiyuren** [comment]
> > 配置的工作目录里面 workingDirPath 里面 有 d8.bat 文件么？ 是不是mac 编译的？AS 最新版吗？
> 
> 是我这边工作路径写错了，少了后面的斜杠，现在报的是这个错误，只生成了这几个文件，0classes business lib dex0classes common dex0classes home dex0classes loading dex0classes_manager dex0classes other dex0classes other2 dex0classes version dex， Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @5a19245c

在gradle 中增加后面的参数就能打出所有的资源包了 -Dfile.encoding=UTF-8 --add-opens ，org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 --add-opens java.base/java.io=ALL-UNNAMED
我这边使用的AS 蜥蜴，考拉可行，主要应该是Java 版本的问题， File | Settings | Build, Execution, Deployment | Build Tools | Gradle 选择gradle JDK jdk11，JDK17 也可以，选择jdk1.8 会打不出所有的包
如果distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip ，就要增加--add-opens ，org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 --add-opens java.base/java.io=ALL-UNNAMED ，在选择jdk11,jdk17的情况下
如果distributionUrl=https\://services.gradle.org/distributions/gradle-7.1-bin.zip  ,就不需要增加-add-opens ，在选择jdk11,jdk17的情况下；不知道怎么配置就按下图的配置
![image](https://github.com/wgllss/WXDynamicPlugin/assets/8176530/c5e9afb9-e40c-4fe6-ad9e-4f49bc6ee6a0)
![image](https://github.com/wgllss/WXDynamicPlugin/assets/8176530/a5b17af6-d8bc-4499-a79d-1ebb9631057a)
![image](https://github.com/wgllss/WXDynamicPlugin/assets/8176530/c6c7ffda-50f8-4714-99c8-8e779c61d40f)
