### ISSUE TITLE
是否支持SDK插件化

### ISSUE THREAD

**Issue by womarklee** [wgllss/WXDynamicPlugin#6]
把宿主相关的资源代码打包成SDK（aar/jar），App只需简单集成这个SDK即可拥有插件化功能，SDK内部可动态加载插件。
Replugin 可以这样使用，比较方便。

**Comment by wgllss** [comment]
你好，感谢提议，看下 我接入指南里面介绍 host [接入指南](https://juejin.cn/post/7372393698230550565) ，Replugin 这个是360的，它这样你可以验证一下，第一次从 进去 从服务端下载 完，到加载进入插件 需要多少时间？下载完后，后面每次host冷启动需要多少时间？它那个同时存在兼容性问题不能全动态化
